version: 2.1

jobs:
  checkout:
    docker:
      - image: circleci/node:8.15-browsers

    working_directory: ~/repo

    steps:
      - checkout

  build:
    docker:
      - image: circleci/node:8.15-browsers

    working_directory: ~/repo

    steps:
      # Download and cache dependencies
      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}

      - run:
          name: npm-install
          command: 'npm install'

      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}

      - run:
          name: Build Storybook
          command: 'npm run build-storybook'

      # Cache the completed build for use in later jobs in this workflow
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repo

workflows:
  version: 2
  vrt:
    jobs:
      - build
        requires:
          - checkout

