version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:current-browsers

    working_directory: ~/repo

jobs:
  install:
    executor: node
    working_directory: ~/repo

    steps:
      - checkout
      - run: 'export APPLITOOLS_BATCH_ID=`echo $CIRCLE_SHA1`'

      # Download and cache dependencies
      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}

      - run:
          name: NPM Install
          command: 'npm install'

      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}

          # Cache the completed build for use in later jobs in this workflow
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repo

  build:
    executor: node
    working_directory: ~/repo

    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Storybook build
          command: 'npm run build-storybook'

  vrt:
    executor: node
    working_directory: ~/repo

    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}

      - run:
          name: Applitools VRT
          command: 'npx eyes-storybook -s node_modules/@salesforce-ux/design-system'

workflows:
  version: 2

  vrt:
    jobs:
      - install
      - build:
          requires:
            - install
      - vrt:
          requires:
            - install
