version: 2.1

executors:
  nodelts:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo

jobs:
  build:
    executor: nodelts

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}

      - run:
          name: npm install
          command: 'npm install'

      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}

      # - run:
      #     name: Build Storybook
      #     command: 'npm run build-storybook'

      - run:
          name: Screener VRT
          command: 'npm run test-storybook'

workflows:
  version: 2

  vrt:
    jobs:
      - build
