version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:current-browsers
    working_directory: ~/repo

jobs:
  install:
    executor: node
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}

      - run:
          name: npm install
          command: 'npm install'

      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}

          # Cache the completed build for use in later jobs in this workflow
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repo

  vrt:
    executor: node
    working_directory: ~/repo

    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}

      - run:
          name: Screener VRT
          command: 'npm run test-storybook'

workflows:
  version: 2

  vrt:
    jobs:
      - install
      - vrt:
          requires:
            - install
