version: 2.1

executors:
  nodelts:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo

jobs:
  # build:
  #   executor: nodelts

  #   steps:
  #     - checkout

  #     # Download and cache dependencies
  #     - restore_cache:
  #         key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}

  #     - run:
  #         name: npm install
  #         command: 'npm install'

  #     - save_cache:
  #         paths:
  #           - node_modules
  #         key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}

  #     - run:
  #         name: Build Storybook
  #         command: 'npm run build-storybook'

  runVRT:
    executor: nodelts

    steps:
      - run: 'export APPLITOOLS_BATCH_ID=`echo $CIRCLE_SHA1`'

      # Download and cache dependencies
      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}

      - run:
          name: NPM Install
          command: 'npm install'

      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}

      - run:
          name: Applitools VRT
          command: 'npx eyes-storybook -s node_modules/@salesforce-ux/design-system'

workflows:
  version: 2

  vrt:
    jobs:
      # - build
      - runVRT
